/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DbAdapterDslRuntimeModule extends AbstractDbAdapterDslRuntimeModule {
}
