/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.hierarchicalgraph.mappingdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MappingDslRuntimeModule extends AbstractMappingDslRuntimeModule {
}
