/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.tests

import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DbAdapterDslInjectorProvider)
class DbAdapterDslParsingTest extends AbstractDbAdapterDefinitionTest {

	@Test
	def void loadModel() {
		test('''
			unmanaged remote database {
				
				// name & description
				name "http://localhost:7474"
				description "Localhost"
				
				//
				uri "http://localhost:7474"
			}
		''')
	}
}
