<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="selection" nsURI="http://org/slizaa/hierarchicalgraph/selection"
    nsPrefix="org.slizaa.hierarchicalgraph.selection">
  <eClassifiers xsi:type="ecore:EClass" name="DependencySelectionStack">
    <eOperations name="canGoForward" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="goForward"/>
    <eOperations name="canGoBack" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="goBack"/>
    <eOperations name="clear"/>
    <eOperations name="setSelection">
      <eParameters name="selection" upperBound="-1" eType="ecore:EClass ../../org.slizaa.hierarchicalgraph/model/hierarchicalgraph.ecore#//AbstractHGDependency"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentSelection" upperBound="-1"
        eType="ecore:EClass ../../org.slizaa.hierarchicalgraph/model/hierarchicalgraph.ecore#//AbstractHGDependency"/>
  </eClassifiers>
</ecore:EPackage>
