/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.slizaa.neo4j.dbadapter.dsl.ui.internal.DslActivator;

public class DbAdapterDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.slizaa.neo4j.dbadapter.dsl.DbAdapterDsl");
	}

}
