<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dbadapter" nsURI="http://org/slizaa/neo4j/dbadapter" nsPrefix="org.slizaa.neo4j.dbadapter">
  <eClassifiers xsi:type="ecore:EClass" name="Neo4jRestClient">
    <eOperations name="getAllRelationshipTypes" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getAllPropertyKeys" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getAllLabels" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getLabelsForNode" eType="#//JsonArray">
      <eParameters name="nodeId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="getPropertiesForNode" eType="#//JsonObject">
      <eParameters name="nodeId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="getPropertiesForRelationship" eType="#//JsonObject">
      <eParameters name="nodeId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="executeCypherQuery">
      <eGenericType eClassifier="#//Future">
        <eTypeArguments eClassifier="#//JsonObject"/>
      </eGenericType>
      <eParameters name="cypherQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="executeCypherQuery">
      <eGenericType eClassifier="#//Future">
        <eTypeArguments eClassifier="#//JsonObject"/>
      </eGenericType>
      <eParameters name="cypherQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="params">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="executeCypherQuery">
      <eGenericType eClassifier="#//Future">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="cypherQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="consumer">
        <eGenericType eClassifier="#//Consumer">
          <eTypeArguments eClassifier="#//JsonObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="executeCypherQuery">
      <eGenericType eClassifier="#//Future">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="cypherQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="params">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eParameters>
      <eParameters name="consumer">
        <eGenericType eClassifier="#//Consumer">
          <eTypeArguments eClassifier="#//JsonObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definingResource" eType="#//IFile"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DbAdapterContainer"
        transient="true" eOpposite="#//DbAdapterContainer/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchicalGraph" eType="ecore:EClass ../../org.slizaa.hierarchicalgraph/model/hierarchicalgraph.ecore#//HGRootNode"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbAdapterRegistry">
    <eOperations name="getDbAdapterContainer" eType="#//DbAdapterContainer">
      <eParameters name="type" lowerBound="1" eType="#//ContainerType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeDbAdapter" eType="#//Neo4jRestClient"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//DbAdapterContainer" containment="true" eOpposite="#//DbAdapterContainer/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbAdapterContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContainerType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DbAdapterRegistry"
        eOpposite="#//DbAdapterRegistry/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Neo4jRestClient" containment="true" eOpposite="#//Neo4jRestClient/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagedNeo4jInstance" eSuperTypes="#//Neo4jRestClient">
    <eOperations name="scan"/>
    <eOperations name="isScanned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="start"/>
    <eOperations name="stop"/>
    <eOperations name="delete"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="running" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directoriesToScan" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="launch" eType="#//ILaunch"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Future" instanceClassName="java.util.concurrent.Future">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Consumer" instanceClassName="java.util.function.Consumer">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JsonArray" instanceClassName="com.google.gson.JsonArray"/>
  <eClassifiers xsi:type="ecore:EDataType" name="JsonObject" instanceClassName="com.google.gson.JsonObject"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ILaunch" instanceClassName="org.eclipse.debug.core.ILaunch"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IFile" instanceClassName="org.eclipse.core.resources.IFile"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ContainerType">
    <eLiterals name="MANAGED"/>
    <eLiterals name="UNMANAGED" value="1"/>
  </eClassifiers>
</ecore:EPackage>
