/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.validation

import org.eclipse.xtext.validation.Check
import org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.mappingDsl.MappingDslPackage
import org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.mappingDsl.StructureDescriptor
import org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.mappingDsl.TopLevelNodesQueries

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MappingDslValidator extends AbstractMappingDslValidator {

	public static val MISSING_TOP_LEVEL_NODE_QUERIES = 'missingTopLevelNodeQueries'

	public static val INVALID_TOP_LEVEL_NODES_QUERY_COUNT = 'invalidTopLevelNodeQueryCount'

	@Check
	def missingTopLevelNodesQueries(StructureDescriptor structureDescriptor) {
		if (structureDescriptor.topLevelNodeQueries == null) {
			error('Missing top level node queries.',
				MappingDslPackage.Literals.STRUCTURE_DESCRIPTOR__TOP_LEVEL_NODE_QUERIES, MISSING_TOP_LEVEL_NODE_QUERIES)
		}
	}

	@Check
	def checkAtLeastOneTopLevelNodesQuery(TopLevelNodesQueries topLevelNodesQueries) {
		if (topLevelNodesQueries.queries.nullOrEmpty) {
			error('At least one top level node query has to be specified.',
				MappingDslPackage.Literals.TOP_LEVEL_NODES_QUERIES__QUERIES, INVALID_TOP_LEVEL_NODES_QUERY_COUNT)
		}
	}
}
