/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.slizaa.neo4j.dbadapter.dsl.parser.antlr.internal.InternalDbAdapterDslParser;
import org.slizaa.neo4j.dbadapter.dsl.services.DbAdapterDslGrammarAccess;

public class DbAdapterDslParser extends AbstractAntlrParser {

	@Inject
	private DbAdapterDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDbAdapterDslParser createParser(XtextTokenStream stream) {
		return new InternalDbAdapterDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DbAdapterDefinition";
	}

	public DbAdapterDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DbAdapterDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
