<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workbenchmodel" nsURI="http://org/slizaa/neo4j/workbenchmodel"
    nsPrefix="org.slizaa.neo4j.workbenchmodel">
  <eClassifiers xsi:type="ecore:EClass" name="WorkbenchModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="databases" lowerBound="1"
        eType="ecore:EClass ../../org.slizaa.neo4j.dbadapter/model/neo4j-dbadapter.ecore#//DbAdapterRegistry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedGraphs" eType="#//MappedGraphs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappedGraphs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="ecore:EClass ../../org.slizaa.hierarchicalgraph/model/hierarchicalgraph.ecore#//HGRootNode"/>
  </eClassifiers>
</ecore:EPackage>
