/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage
 * @generated
 */
public interface DbAdapterDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DbAdapterDslFactory eINSTANCE = org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.impl.DbAdapterDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Db Adapter Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Db Adapter Definition</em>'.
   * @generated
   */
  DbAdapterDefinition createDbAdapterDefinition();

  /**
   * Returns a new object of class '<em>Unmanaged Remote Database</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unmanaged Remote Database</em>'.
   * @generated
   */
  UnmanagedRemoteDatabase createUnmanagedRemoteDatabase();

  /**
   * Returns a new object of class '<em>Managed Local Database</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Managed Local Database</em>'.
   * @generated
   */
  ManagedLocalDatabase createManagedLocalDatabase();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DbAdapterDslPackage getDbAdapterDslPackage();

} //DbAdapterDslFactory
