/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Managed Local Database</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.ManagedLocalDatabase#getPort <em>Port</em>}</li>
 *   <li>{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.ManagedLocalDatabase#getStorage <em>Storage</em>}</li>
 *   <li>{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.ManagedLocalDatabase#getFiles <em>Files</em>}</li>
 * </ul>
 *
 * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage#getManagedLocalDatabase()
 * @model
 * @generated
 */
public interface ManagedLocalDatabase extends DbAdapterDefinition
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage#getManagedLocalDatabase_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.ManagedLocalDatabase#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Storage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Storage</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Storage</em>' attribute.
   * @see #setStorage(String)
   * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage#getManagedLocalDatabase_Storage()
   * @model
   * @generated
   */
  String getStorage();

  /**
   * Sets the value of the '{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.ManagedLocalDatabase#getStorage <em>Storage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Storage</em>' attribute.
   * @see #getStorage()
   * @generated
   */
  void setStorage(String value);

  /**
   * Returns the value of the '<em><b>Files</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Files</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Files</em>' attribute list.
   * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage#getManagedLocalDatabase_Files()
   * @model unique="false"
   * @generated
   */
  EList<String> getFiles();

} // ManagedLocalDatabase
