/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unmanaged Remote Database</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.UnmanagedRemoteDatabase#getUri <em>Uri</em>}</li>
 * </ul>
 *
 * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage#getUnmanagedRemoteDatabase()
 * @model
 * @generated
 */
public interface UnmanagedRemoteDatabase extends DbAdapterDefinition
{
  /**
   * Returns the value of the '<em><b>Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uri</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri</em>' attribute.
   * @see #setUri(String)
   * @see org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.DbAdapterDslPackage#getUnmanagedRemoteDatabase_Uri()
   * @model
   * @generated
   */
  String getUri();

  /**
   * Sets the value of the '{@link org.slizaa.neo4j.dbadapter.dsl.dbAdapterDsl.UnmanagedRemoteDatabase#getUri <em>Uri</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uri</em>' attribute.
   * @see #getUri()
   * @generated
   */
  void setUri(String value);

} // UnmanagedRemoteDatabase
