/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.dbadapter.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DbAdapterDslStandaloneSetup extends DbAdapterDslStandaloneSetupGenerated {

	def static void doSetup() {
		new DbAdapterDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
