/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.tests

import org.junit.Test

class MetaInformationTest extends AbstractMappingDslParsingTest {

	@Test
	def void testMetaInformation() {
		test('''
			mapping org.slizza.jqassistant.java.HierachicalPackagesMapping {
					name "A name"
					description "A description"
			}
		''')
	}
	
	@Test
	def void testMetaInformation_Name() {
		test('''
			mapping org.slizza.jqassistant.java.HierachicalPackagesMapping {
					name "A name"
			}
		''')
	}
	
	@Test
	def void testMetaInformation_Description() {
		test('''
			mapping org.slizza.jqassistant.java.HierachicalPackagesMapping {
					description "A description"
			}
		''')
	}
}
