/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.tests

import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith
import org.slizaa.neo4j.hierarchicalgraph.mapping.dsl.mappingDsl.MappingDslPackage

@RunWith(XtextRunner)
@InjectWith(MappingDslInjectorProvider)
class StructureTest extends AbstractMappingDslParsingTest {

	@Test
	def void emptyStructureBlock() {
		testAssertError('''
			mapping org.slizza.jqassistant.java.HierachicalPackagesMapping {
				structure {
					// empty
				}
			}
		''', MappingDslPackage.eINSTANCE.structureDescriptor, 'missingTopLevelNodeQueries', 67, 27,
			'Missing top level node queries.')
	}

	@Test
	def void emptyTopLevelNodeQueries() {
		testAssertError('''
			mapping org.slizza.jqassistant.java.HierachicalPackagesMapping {
				structure {
					topLevelNodeQueries {
						// empty
					}		
				}
			}
		''', MappingDslPackage.eINSTANCE.topLevelNodesQueries, 'invalidTopLevelNodeQueryCount', 82, 39,
			'At least one top level node query has to be specified.')
	}

}
